-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN "documentType" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "bucket" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "confirmed" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Invoice" ADD COLUMN "eDocument" TEXT NOT NULL DEFAULT 'e-Arşiv';
ALTER TABLE "Invoice" ADD COLUMN "scenario" TEXT NOT NULL DEFAULT 'TEMELFATURA';
ALTER TABLE "Invoice" ADD COLUMN "series" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'TRY';
ALTER TABLE "Invoice" ADD COLUMN "fxRate" DOUBLE PRECISION NOT NULL DEFAULT 1;
ALTER TABLE "Invoice" ADD COLUMN "partyTaxNo" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "partyTaxOffice" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "partyAddress" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "partyCity" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "partyDistrict" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "partyPhone" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "partyEmail" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "sellerName" TEXT NOT NULL DEFAULT 'HamdPharma';
ALTER TABLE "Invoice" ADD COLUMN "sellerTaxNo" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "sellerTaxOffice" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "sellerAddress" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "paymentMethod" TEXT NOT NULL DEFAULT 'Cari hesap';
ALTER TABLE "Invoice" ADD COLUMN "relatedDispatchNo" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "relatedOrderNo" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "notes" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "subtotal" DECIMAL(18,4) NOT NULL DEFAULT 0;
ALTER TABLE "Invoice" ADD COLUMN "totalDiscount" DECIMAL(18,4) NOT NULL DEFAULT 0;
ALTER TABLE "Invoice" ADD COLUMN "totalVat" DECIMAL(18,4) NOT NULL DEFAULT 0;
ALTER TABLE "Invoice" ADD COLUMN "withholding" DECIMAL(18,4) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "InvoiceLine" ADD COLUMN "quantity" DOUBLE PRECISION NOT NULL DEFAULT 1;
ALTER TABLE "InvoiceLine" ADD COLUMN "unit" TEXT NOT NULL DEFAULT 'Adet';
ALTER TABLE "InvoiceLine" ADD COLUMN "discountRate" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "InvoiceLine" ADD COLUMN "vatRate" DOUBLE PRECISION NOT NULL DEFAULT 20;
ALTER TABLE "InvoiceLine" ADD COLUMN "vatAmount" DECIMAL(18,4) NOT NULL DEFAULT 0;
ALTER TABLE "InvoiceLine" ADD COLUMN "lineNet" DECIMAL(18,4) NOT NULL DEFAULT 0;
